import time
print("Welcome to Google Forms")
Fn=str(input("Enter first name "))
Ln=str(input("Enter Your Last name "))
age=int(input("Enter your age "))
city=str(input("Enter your city "))
state=str(input("Enter your state "))
zipcodes=str(input("Enter your Zipcodes "))
Address=str(input("Enter your Address "))
print("Loading....")
time.sleep(6)
print("Hello",Fn,Ln,)
time.sleep(1)
print("You are",age,"years old")
time.sleep(1)
print("And you are in",city,state,)
time.sleep(1)
print("Your code is",zipcodes)
time.sleep(1)
print("And your house address is",Address)
time.sleep(1)
print("The Google Team will visit you in",city)
time.sleep(1)
print("They will give you a new zipcodes instead of this",{zipcodes})
time.sleep(1)
