import time
print("Send Money To Other Countries For Free")
time.sleep(2)
a=["Ghana,Gabon,Gambia,Togo,India,Nigeria,Niger,Angola,Botswanna"]
print(a)
b=str(input("Select a Country: "))
if(b==("Ghana")):
    num1=str(input("Enter your Number {Number should include the country Code}: "))
    if(num1.__contains__("+")):
        print("Loading....")
        time.sleep(2)
        canum=int(input("Enter your Card Number: "))
        you=str(input("Write your Name: "))
        person=str(input("Enter the Person name you are sending the money: "))
        personnum=int(input("Enter the His/Her Number: "))
        much=int(input("How much do you want to send?: "))
        print("Loading....")
        time.sleep(3)
        print("In progress......")
        time.sleep(4)
        print("Hold on....")
        time.sleep(4)
        print("Almost there....")
        time.sleep(3)
        print("Hi",you)
        print("You are sending money to",person)
        print(much,"$","is the amount you are sending")
        time.sleep(2)
        prompt=str(input("Enter your Pin to Complete: "))
        time.sleep(4)
        print("Loading....")
        time.sleep(1)
        print("You have Successfully Send Money to\n",person)
    else:
        print("A Country Number Must Include '+'!")
elif(b==("Gabon")):
    num2=str(input("Enter your Number {Number should include the country Code}: "))
    if(num2.__contains__("+")):
        print("Loading....")
        time.sleep(2)
        canum1=int(input("Enter your Card Number: "))
        you1=str(input("Write your Name: "))
        person1=str(input("Enter the Person name you are sending the money: "))
        personnum1=int(input("Enter the His/Her Number: "))
        much1=int(input("How much do you want to send?: "))
        print("Loading....")
        time.sleep(3)
        print("In progress......")
        time.sleep(4)
        print("Hold on....")
        time.sleep(4)
        print("Almost there....")
        time.sleep(3)
        print("Hi",you1)
        print("You are sending money to",person1)
        print(much1,"$","is the amount you are sending")
        time.sleep(2)
        prompt=str(input("Enter your Pin to Complete: "))
        time.sleep(4)
        print("Loading....")
        time.sleep(1)
        print("You have Successfully Send Money to\n",person1)
elif(b==("Gambia")):
    num3=str(input("Enter your Number {Number should include the country Code}: "))
    if(num3.__contains__("+")):
        print("Loading....")
        time.sleep(2)
        canum2=int(input("Enter your Card Number: "))
        you2=str(input("Write your Name: "))
        person2=str(input("Enter the Person name you are sending the money: "))
        personnum2=int(input("Enter the His/Her Number: "))
        much1=int(input("How much do you want to send?: "))
        print("Loading....")
        time.sleep(3)
        print("In progress......")
        time.sleep(4)
        print("Hold on....")
        time.sleep(4)
        print("Almost there....")
        time.sleep(3)
        print("Hi",you2)
        print("You are sending money to",person2)
        print(much1,"$","is the amount you are sending")
        time.sleep(2)
        prompt=str(input("Enter your Pin to Complete: "))
        time.sleep(4)
        print("Loading....")
        time.sleep(1)
        print("You have Successfully Send Money to\n",person2)
elif(b==("Togo")):
    num4=str(input("Enter your Number {Number should include the country Code}: "))
    if(num4.__contains__("+")):
        print("Loading....")
        time.sleep(2)
        canum3=int(input("Enter your Card Number: "))
        you3=str(input("Write your Name: "))
        person3=str(input("Enter the Person name you are sending the money: "))
        personnum3=int(input("Enter the His/Her Number: "))
        much3=int(input("How much do you want to send?: "))
        print("Loading....")
        time.sleep(3)
        print("In progress......")
        time.sleep(4)
        print("Hold on....")
        time.sleep(4)
        print("Almost there....")
        time.sleep(3)
        print("Hi",you3)
        print("You are sending money to",person3)
        print(much3,"$","is the amount you are sending")
        time.sleep(2)
        prompt=str(input("Enter your Pin to Complete: "))
        time.sleep(4)
        print("Loading....")
        time.sleep(1)
        print("You have Successfully Send Money to\n",person3) 
elif(b==("India")):
    num5=str(input("Enter your Number {Number should include the country Code}: "))
    if(num5.__contains__("+")):
        print("Loading....")
        time.sleep(2)
        canum4=int(input("Enter your Card Number: "))
        you4=str(input("Write your Name: "))
        person4=str(input("Enter the Person name you are sending the money: "))
        personnum4=int(input("Enter the His/Her Number: "))
        much4=int(input("How much do you want to send?: "))
        print("Loading....")
        time.sleep(3)
        print("In progress......")
        time.sleep(4)
        print("Hold on....")
        time.sleep(4)
        print("Almost there....")
        time.sleep(3)
        print("Hi",you4)
        print("You are sending money to",person4)
        print(much4,"$","is the amount you are sending")
        time.sleep(2)
        prompt=str(input("Enter your Pin to Complete: "))
        time.sleep(4)
        print("Loading....")
        time.sleep(1)
        print("You have Successfully Send Money to\n",person4)
elif(b==("Nigeria")):
    num6=str(input("Enter your Number {Number should include the country Code}: "))
    if(num6.__contains__("+")):
        print("Loading....")
        time.sleep(2)
        canum5=int(input("Enter your Card Number: "))
        you5=str(input("Write your Name: "))
        person5=str(input("Enter the Person name you are sending the money: "))
        personnum5=int(input("Enter the His/Her Number: "))
        much4=int(input("How much do you want to send?: "))
        print("Loading....")
        time.sleep(3)
        print("In progress......")
        time.sleep(4)
        print("Hold on....")
        time.sleep(4)
        print("Almost there....")
        time.sleep(3)
        print("Hi",you5)
        print("You are sending money to",person5)
        print(much4,"$","is the amount you are sending")
        time.sleep(2)
        prompt=str(input("Enter your Pin to Complete: "))
        time.sleep(4)
        print("Loading....")
        time.sleep(1)
        print("You have Successfully Send Money to\n",person5) 
elif(b==("Niger")):
    num7=str(input("Enter your Number {Number should include the country Code}: "))
    if(num7.__contains__("+")):
        print("Loading....")
        time.sleep(2)
        canum6=int(input("Enter your Card Number: "))
        you6=str(input("Write your Name: "))
        person6=str(input("Enter the Person name you are sending the money: "))
        personnum6=int(input("Enter the His/Her Number: "))
        much4=int(input("How much do you want to send?: "))
        print("Loading....")
        time.sleep(3)
        print("In progress......")
        time.sleep(4)
        print("Hold on....")
        time.sleep(4)
        print("Almost there....")
        time.sleep(3)
        print("Hi",you6)
        print("You are sending money to",person6)
        print(much4,"$","is the amount you are sending")
        time.sleep(2)
        prompt=str(input("Enter your Pin to Complete: "))
        time.sleep(4)
        print("Loading....")
        time.sleep(1)
        print("You have Successfully Send Money to\n",person6) 
elif(b==("Angola")):
    num8=str(input("Enter your Number {Number should include the country Code}: "))
    if(num8.__contains__("+")):
        print("Loading....")
        time.sleep(2)
        canum7=int(input("Enter your Card Number: "))
        you7=str(input("Write your Name: "))
        person7=str(input("Enter the Person name you are sending the money: "))
        personnum7=int(input("Enter the His/Her Number: "))
        much7=int(input("How much do you want to send?: "))
        print("Loading....")
        time.sleep(3)
        print("In progress......")
        time.sleep(4)
        print("Hold on....")
        time.sleep(4)
        print("Almost there....")
        time.sleep(3)
        print("Hi",you7)
        print("You are sending money to",person7)
        print(much7,"$","is the amount you are sending")
        time.sleep(2)
        prompt=str(input("Enter your Pin to Complete: "))
        time.sleep(4)
        print("Loading....")
        time.sleep(1)
        print("You have Successfully Send Money to\n",person7) 
elif(b==("Botswanna")):
    num9=str(input("Enter your Number {Number should include the country Code}: "))
    if(num9.__contains__("+")):
        print("Loading....")
        time.sleep(2)
        canum8=int(input("Enter your Card Number: "))
        you8=str(input("Write your Name: "))
        person8=str(input("Enter the Person name you are sending the money: "))
        personnum8=int(input("Enter the His/Her Number: "))
        much8=int(input("How much do you want to send?: "))
        print("Loading....")
        time.sleep(3)
        print("In progress......")
        time.sleep(4)
        print("Hold on....")
        time.sleep(4)
        print("Almost there....")
        time.sleep(3)
        print("Hi",you8)
        print("You are sending money to",person8)
        print(much8,"$","is the amount you are sending")
        time.sleep(2)
        prompt=str(input("Enter your Pin to Complete: "))
        time.sleep(4)
        print("Loading....")
        time.sleep(1)
        print("You have Successfully Send Money to\n",person8) 
else:
    print("Please Select a Country")