import time
nam=str(input("What's your name? "))
fn=str(input("What's your friend's name? "))
nampa=str(input("What's your parent's name? "))
fnpa=str(input("What's your friend's parent's name? "))
print("Here my story...")
time.sleep(3)
print("Once upon a time,in the afternoon")
time.sleep(3)
print("There lived two good friends named",nam,"and",fn)
time.sleep(3)
print("One day,",nam,"wanted to bite",fn)
time.sleep(3)
print(fn,"reported to his parents")
time.sleep(3)
print(fnpa,"said they will tell",nampa)
time.sleep(4)
print(nam,"was very scared of what",nampa,"would do to him")
time.sleep(4)
print("So",nam,"started thinking what to do")
time.sleep(3)
print("finally, he got an idea")
time.sleep(3)
print(nam,"said'he would lie'")
time.sleep(4)
print("So that,everning",fn,"and",fnpa,"came to",nam,"house")
time.sleep(4)
print(fnpa,"reported this to",nampa)
time.sleep(4)
print(nampa,"told",nam,"that is this true?")
time.sleep(4)
print("But",nam,"lied and said this wasn't true")
time.sleep(4)
print(fn,"said 'its true',he bite me when we were playing")
time.sleep(4)
print(nam,"still insisted that it wasn't him")
time.sleep(4)
print("ok,",nampa,"said, we will see what to do")
time.sleep(4)
print("Come back tomorrow",fn,"and",fnpa,"we shall discuss this tomorrow")
time.sleep(4)
print(fn,"and",fnpa,"left the house")
time.sleep(4)
print("NEXT DAY....")
time.sleep(4)
print(fn,"and",fnpa,"came to",nam,"house")
time.sleep(3)
print(fn,"was so angry than usual")
time.sleep(3)
print(nampa,"said'ok,shall we contine'")
print("let's do this, we are going to have 'Zuluk'!")
time.sleep(5)
print("At that moment, everyone got confused.",fnpa,"said, what's Zuluk?")
time.sleep(4)
print("is a litte game that we play,said",nampa)
time.sleep(3)
print("It goes like this,",fn,"and",nam,"are going to pour water into this bottles")
print("With these spoons")
time.sleep(5)
print(fn,"said,how is that possible",nampa,"said,oh is easy.\n you just have to take the water with the spoons \n and put it into the bottles.")
time.sleep(3)
print(nampa,"said start....now!")
time.sleep(3)
print(nam,"and",fn,"were pouring water into the bottles")
time.sleep(4)
print("Few minutes later....")
time.sleep(4)
print(nampa,"came to see their bottles.\n it turns out that",nam,"was lying")
time.sleep(3)
print(nam,"said,I'm so sorry.",nampa,"said,its okay.")
time.sleep(3)
print("I'm sorry for biting you",fn,"its all right.said",fn)
time.sleep(3)
print("Now,you two don't go and hurt each other again.said",nampa)
time.sleep(3)
print("And so",nam,"and",fn,"went out to play.")
time.sleep(3)
print(nam,"learnt his lesson.")
time.sleep(3)
print("And THAT IS WHERE MY STORY ENDS!")